name: CI

on:
  push:
    branches:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test Markdown
        run: npm run test:markdown

      - name: Build
        run: npm run build

      - name: Upload GitHub Pages artifacts
        uses: actions/upload-artifact@v1
        if: github.ref == 'refs/heads/main' &&
            github.repository == 'costrojs/costrojs.github.io' &&
            github.event_name != 'pull_request'
        with:
          name: docs
          path: build
